stages:
- build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - mkdir ~/.docker/
    - touch ~/.docker/config.json
    - echo $DOCKER_AUTH_CONFIG >> ~/.docker/config.json
build:dev:
  stage: build
  image: tharegorn/nginx_test
  script:
    - docker run --name tharegorn/nginx_test -p localhost:80:80 -it nginx_test


