apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonLabels:
  env: dev

resources:
- namespace.yml
- ../../base
namespace: dev
images:
- name: backend-app
  newName: tharegorn/nginx_test
  newTag: 15971e3a
