apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonLabels:
  env: dev

resources:
- namespace.yml
- ../../base
namespace: dev

secretGenerator:
  - name: regcred
    files:
      - ./config.json
images:
- name: backend-app
  newName: tharegorn/nginx_test
  newTag: 2c7f661c
  imagePullSecrets:
  - name: regcred
