apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx_test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx_test
  template:
    metadata:
      labels:
        app: nginx_test
    spec:
      # imagePullSecrets:
      # - name: regcred
      containers:
      - name: nginx-test
        image: backend-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
