apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: tharegorn/nginx_test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tharegorn/nginx_test
  template:
    metadata:
      labels:
        app: tharegorn/nginx_test
    spec:
      containers:
      - name: tharegorn/nginx_test
        image: nginx
        ports:
        - containerPort: 80